### ISSUE TITLE
Munkanapló

### ISSUE THREAD

**Issue by FP5i** [BME-MIT-IET/Hat-meg-IET-iet-2019#52]
@Sydnikat, @marazmarci, @LPeter1997 kérlek írjátok le, hogy melyik feladatattal mikor és mennyit foglalkoztatok

**Comment by FP5i** [comment]
##### Mindenki
Csapatmegbeszélés 04.05 ****1**** óra
- csapatnév
- projekt választása
- projekt első kis áttenkintése

A projekt megismerése 04.17 **1,5** óra
- A CppCmb áttenkintése példákon keresztül

#### Fónad Péter
Milestone-k és issuek megírása 04.20 **0,5** óra
Példakódok:
- magyar telefonszámok: 04.26 **0,5** óra
- JSON validátor: 04.27 **1,5** óra

Travis beüzemelés: 04.28 **7,5** óra
- megismerése, dokumetáció olvasása
- yml megírása

Unit tesztek a Travisba: 05.08 **0,5** óra

Unit tesztek kérszítése: **2** óra
- `pc::one`
- lazy alternative

Egyéb Travis: **1-2** óra
Dokumentációk írása: **0,5** óra 
Összesen: *17* óra

**Comment by FP5i** [comment]
#### Fónad Péter
Milestone-k és issuek megírása 04.20 **0,5** óra
Példakódok:
- magyar telefonszámok: 04.26 **0,5** óra
- JSON validátor: 04.27 **1,5** óra

Travis beüzemelés: 04.28 **7,5** óra
- megismerése, dokumetáció olvasása
- yml megírása

Unit tesztek a Travisba: 05.08 **0,5** óra

Unit tesztek kérszítése: 05.08 **2** óra
- `pc::one`
- lazy alternative

Egyéb Travis: **1,5** óra
Dokumentációk írása: **0,5** óra 

Összesen: **17** óra

**Comment by FP5i** [comment]
#### Maráz Márton
Példakódok írása:
- scientific notation: 05.10. **1** óra
- brainfuck interpreter: 05.12-14. **8** óra

CMake setup: 04.28 **1** óra

Unit tesztek kérszítése: 05.08 **1.5** óra
- sequence
- optional: (+05.14-én javítás)

BDD teszt (scientific notation): 05.18. **1** óra

Dokumentációk írása: **1** óra 

Összesen: **16** óra

**Comment by Sydnikat** [comment]
**Szalai Dávid**

Példakódok megírása:

- e-mail címek: 04.27. **1.5** óra
- egyszerű CF nyelvtan: 04.27. **0.5** óra

Appveyor beüzemelése: 

-  yaml megismerése, dokumentáció olvasása/megértése: 04.29 **6.5** óra
- appveyor.yml megírása: 04.30. **1.5** óra

Unit tesztek az appveyor-ba: 05.08. **1** óra

Unit tesztek készítése: 05.08. **1.5** óra

- `pc::end`
- `||` (eager alternative)

Dokumentációk írása: **1** óra

Összesen: **16** óra

**Comment by LPeter1997** [comment]
#### Lenkefi Péter
Készülés a csapatmegbeszélésre (a library bemutatása): 04.03. **2** óra

Példakódok:
- C identifier: 04.24. **0,5** óra
- Boole-algebra: 04.24. **1** óra
- Példakódok átnézése: **2** óra

Static Code Analysis:
- "egyszerűbb" tool-ok: 04.29. **1** óra
- `clang-tidy`: 04.29. **2** óra
- A library-ben a `clang-tidy` hibák javítása: 04.30. **2** óra

Tesztek írása: 05.08. **1** óra
- `many`
- `many1`
- `action`

Coverage report: 05.10. - 05.14.
- A gcov/lcov és egyéb tool-ok megismerése: **3** óra
- A build rendszer és travis módosírása: **1** óra
- Debug: **3** óra

Dokumentáció: **1** óra

**Összesen: *19 óra*
